services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "web"
    ports:
      - 8000:80
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
    env_file:
      - .env
  worker:
    build: 
      context: ./ImageProcessor
      dockerfile: Dockerfile
    container_name: "worker"
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq

networks:
  mynetwork: