services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - rabbitmq
    env_file:
      - .env
  worker:
    build: 
      context: ./ImageProcessor
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq